package com.UI.Admin;

import java.awt.BorderLayout;
import java.awt.EventQueue;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

import com.admin.services.BankService;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

public class SearchEmployee extends javax.swing.JFrame {

	static BankService bs = new BankService();
	static int id;

	static ArrayList result;

	public SearchEmployee() {
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {
		result = bs.showSpecific(id);
		String ename = (String) result.get(0);
		String fname = (String) result.get(1);
		String gender = (String) result.get(2);
		Date dob = (Date) result.get(3);
		String blood = (String) result.get(4);
		String pan = (String) result.get(5);
		String aadhar = (String) result.get(6);
		String address = (String) result.get(7);
		String phone = (String) result.get(8);
		String email = (String) result.get(9);
		String marital = (String) result.get(10);
		String id1 = result.get(11).toString();

		jPanel1 = new javax.swing.JPanel();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jLabel13 = new javax.swing.JLabel();
		jLabel30 = new javax.swing.JLabel();
		jLabel31 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jSeparator1 = new javax.swing.JSeparator();
		jButton4 = new javax.swing.JButton();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		jLabel23 = new javax.swing.JLabel();
		jLabel24 = new javax.swing.JLabel();
		jLabel25 = new javax.swing.JLabel();
		jLabel26 = new javax.swing.JLabel();
		jLabel27 = new javax.swing.JLabel();
		jLabel28 = new javax.swing.JLabel();
		jLabel29 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setUndecorated(true);

		jPanel1.setBackground(new java.awt.Color(0, 102, 102));

		jButton2.setBackground(new java.awt.Color(0, 102, 102));
		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back-icon.png"))); // NOI18N
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setBackground(new java.awt.Color(0, 102, 102));
		jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/symbol-delete-icon.png"))); // NOI18N
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
		jLabel13.setForeground(new java.awt.Color(255, 255, 255));
		jLabel13.setText("Employee Info");

		jLabel30.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel30.setForeground(new java.awt.Color(255, 255, 255));
		jLabel30.setText(" ID :");

		jLabel31.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel31.setForeground(new java.awt.Color(255, 255, 255));
		jLabel31.setText(id1);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel13)
						.addGap(39, 39, 39)
						.addComponent(jLabel30)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jLabel31)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
						.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
								.addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(28, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel13)
								.addComponent(jLabel30)
								.addComponent(jLabel31))
						.addGap(24, 24, 24))
				);

		jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel1.setText("Designation");

		jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel2.setText("Name");

		jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel3.setText("Father's Name");

		jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel4.setText("Gender");

		jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel5.setText("DOB");

		jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel7.setText("Pan Card No.");

		jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel8.setText("Aadhar Card No.");

		jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel9.setText("Address");

		jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel10.setText("Phone No.");

		jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel11.setText("Email");

		jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel12.setText("Marital Status");

		jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel6.setText("Blood Group");

		jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jButton1.setText("Edit");
		jButton1.setMaximumSize(new java.awt.Dimension(75, 27));
		jButton1.setMinimumSize(new java.awt.Dimension(75, 27));
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jButton4.setText("Delete");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		String designation = null;
		if(id>6000 && id<1000)
		{
			JOptionPane.showMessageDialog(null, "ID NOT Found. \nPlease Enter a valid ID");
			AdminMenu.main(null);
			dispose();
		}
		else if(id>5000)
			designation = "Loan Officer";
		else if(id>4000)
			designation = "Data Entry officer";
		else if(id>3000)
			designation = "Manager";
		else if(id>2000)
			designation = "Auditor";
		else if(id>1000)
			designation = "Teller";
		jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel14.setText(designation);

		jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel15.setText(ename);

		jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel16.setText(fname);

		jLabel17.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel17.setText(gender);

		jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		/*DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
		String dob = df.format(d);*/
		jLabel18.setText(dob.toString());

		jLabel23.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel23.setText(blood);

		jLabel24.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel24.setText(pan);

		jLabel25.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel25.setText(aadhar);

		jLabel26.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel26.setText(address);

		jLabel27.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel27.setText(phone);

		jLabel28.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel28.setText(email);

		jLabel29.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		jLabel29.setText(marital);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3Layout.setHorizontalGroup(
			jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup()
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel2)
								.addComponent(jLabel1))
							.addGap(95)
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel14)
								.addComponent(jLabel15)))
						.addGroup(jPanel3Layout.createSequentialGroup()
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel4)
								.addComponent(jLabel3)
								.addComponent(jLabel5)
								.addComponent(jLabel6)
								.addComponent(jLabel7)
								.addComponent(jLabel8)
								.addComponent(jLabel9))
							.addGap(68)
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING, false)
								.addComponent(jLabel26, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel25, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel24, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel23, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel16, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel17, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel18, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addGroup(jPanel3Layout.createSequentialGroup()
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel11)
								.addComponent(jLabel10)
								.addComponent(jLabel12))
							.addGap(83)
							.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel29)
								.addComponent(jLabel27)
								.addComponent(jLabel28))))
					.addGap(175))
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addGap(113)
					.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)
					.addGap(95)
					.addComponent(jButton4))
		);
		jPanel3Layout.setVerticalGroup(
			jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel1)
						.addComponent(jLabel14))
					.addGap(42)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel2)
						.addComponent(jLabel15))
					.addGap(42)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel3)
						.addComponent(jLabel16))
					.addGap(42)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel4)
						.addComponent(jLabel17))
					.addGap(42)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jLabel5)
						.addComponent(jLabel18))
					.addGap(42)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jLabel6)
						.addComponent(jLabel23))
					.addGap(42)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jLabel7)
						.addComponent(jLabel24))
					.addGap(42)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jLabel8)
						.addComponent(jLabel25))
					.addGap(42)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel9)
						.addComponent(jLabel26))
					.addGap(92)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel10)
						.addComponent(jLabel27))
					.addGap(44)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel11)
						.addComponent(jLabel28))
					.addGap(62)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jLabel12)
						.addComponent(jLabel29))
					.addPreferredGap(ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton4))
					.addGap(31)
					.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addContainerGap())
		);
		jPanel3.setLayout(jPanel3Layout);

		jScrollPane2.setViewportView(jPanel3);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE))
				);

		pack();
	}// </editor-fold>                        

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		AdminMenu.main(null);
		dispose();
	}                                        

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		System.exit(0);
	}                                        

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		EditEmployee.main(null);
		dispose();
	}                                        

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		int ans = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete?","Delete Employee", WIDTH);
		if(ans==0)
		{
			int a = bs.Delete(id);
			if(a==1)
				JOptionPane.showMessageDialog(null, "Successful");
		}
	}                                        

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		id = Integer.parseInt( JOptionPane.showInputDialog("Enter ID") );
		result = bs.showSpecific(id);
		if( !result.isEmpty() )
		{
			try {
				for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
					if ("Nimbus".equals(info.getName())) {
						javax.swing.UIManager.setLookAndFeel(info.getClassName());
						break;
					}
				}
			} catch (ClassNotFoundException ex) {
				java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
			} catch (InstantiationException ex) {
				java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
			} catch (IllegalAccessException ex) {
				java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
			} catch (javax.swing.UnsupportedLookAndFeelException ex) {
				java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
			}
			//</editor-fold>

			/* Create and display the form */
			java.awt.EventQueue.invokeLater(new Runnable() {
				public void run() {
					new SearchEmployee().setVisible(true);
				}
			});
		}
		else
		{
			JOptionPane.showMessageDialog(null, "ID NOT Found. \nPlease Enter a valid ID");
			AdminMenu.main(null);
		}
	}

	// Variables declaration - do not modify                     
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel jLabel25;
	private javax.swing.JLabel jLabel26;
	private javax.swing.JLabel jLabel27;
	private javax.swing.JLabel jLabel28;
	private javax.swing.JLabel jLabel29;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel30;
	private javax.swing.JLabel jLabel31;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JSeparator jSeparator1;
	// End of variables declaration                   
}
